version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: container/Dockerfile
    image: adsgem-apis-main-backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB_Test=testdb
      - AZURE_GPT_API_KEY=${AZURE_GPT_API_KEY}
      - AZURE_GPT_API_ENDPOINT=${AZURE_GPT_API_ENDPOINT}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - COMFY_SERVER_URL=${COMFY_SERVER_URL}
    volumes:
      - ./backend/src:/app/src
      - ./backend/alembic:/app/alembic
    restart: unless-stopped

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: container/Dockerfile
    image: adsgem-apis-main-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
